export const LIST_BRIDGE = 'LIST_BRIDGE';
export const LIST_NODE_BY_BRIDGE = 'LIST_NODE_BY_BRIDGE';
export const LIST_SELECT_NODE_BY_BRIDGE = 'LIST_SELECT_NODE_BY_BRIDGE';
export const LIST_INTERFACE_BY_BRIDGE = 'LIST_INTERFACE_BRIDGE';
export const LIST_SELECT_INTERFACE_BY_BRIDGE =
  'LIST_SELECT_INTERFACE_BY_BRIDGE';

export const LIST_INTERFAE = 'LIST_INTERFACE';
export const SELECT_BRIDGE = 'SELECT_BRIDGE';
export const MESSAGE = 'MESSAGE';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
