export const FETCH_LIST_BRIDGE_OSPF = 'FETCH_LIST_BRIDGE_OSPF';
export const FETCH_LIST_NODE_BRIDGE_OSPF = 'FETCH_LIST_NODE_BRIDGE_OSPF';
export const MESSAGE_DATA_OSPF = 'MESSAGE_DATA_OSPF';
export const STATUS_DATA_OSPF = 'STATUS_DATA_OSPF';
