export const FETCH_LIST_BRIDGE_VXLAN = 'FETCH_LIST_BRIDGE_VXLAN';
export const FETCH_LIST_NODE_BRIDGE_VXLAN = 'FETCH_LIST_NODE_BRIDGE_VXLAN';
export const MESSAGE_DATA_VXLAN = 'MESSAGE_DATA_VXLAN';
export const STATUS_DATA_VXLAN = 'STATUS_DATA_VXLAN';
