export const LIST_BRIDGE_DOMAIN = 'LIST_BRIDGE_DOMAIN';
export const LIST_NODE_BY_BRIDGE_DOMAIN = 'LIST_NODE_BY_BRIDGE_DOMAIN';
export const LIST_INTERFACE_BY_BRIDGE_DOMAIN =
  'LIST_INTERFACE_BY_BRIDGE_DOMAIN';
export const MESSAGE_DATA = 'MESSAGE_DATA';
export const STATUS_DATA = 'STATUS_DATA';
